# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: jd_updateCFD

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1,8,16 * * *'
  watch:
    types: started
  repository_dispatch:
    types: jd_updateCFD
jobs:
  build:
    env:
      dst_key: ${{ secrets.GITEE_PRIVATE_KEY }} # 我自己同步到gitee使用，其他人可忽略
    runs-on: ubuntu-latest

    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false 
          fetch-depth: 0
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【更新财富岛】'
        run: |
          node jd_updateCfd.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JD_DEBUG: ${{ secrets.JD_DEBUG }}
      - name: commit
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "update by Action" -a || echo "Nothing to update"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: master
      - name: Purge CDN Cache
        run: curl https://purge.jsdelivr.net/gh/DX3242/updateTeam@master/shareCodes/cfd.json
      # 我自己同步到gitee使用，其他人可忽略
      - name: sync github -> gitee
        uses: Yikun/hub-mirror-action@master
        if: env.dst_key
        with:
          src: ${{ secrets.SRC_USER }}
          dst: ${{ secrets.DST_USER }}
          static_list: "updateTeam"
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}   